/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.game.bg {
    export class FarbgSceneUI extends Scene {
		public bg1:Laya.Box;
		public bg2:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/bg/FarbgScene");
        }
    }
    REG("ui.game.bg.FarbgSceneUI",FarbgSceneUI);
    export class NearWaterSceneUI extends Scene {
		public box_game:Laya.Box;
		public box_:Laya.Box;
		public box_mwav:Laya.Box;
		public mwav1:Laya.Box;
		public mwav2:Laya.Box;
		public icon_player:Laya.Image;
		public icon_enemy:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/bg/NearWaterScene");
        }
    }
    REG("ui.game.bg.NearWaterSceneUI",NearWaterSceneUI);
}
export module ui.game.blood {
    export class PlayerBloodUI extends Scene {
		public icon_blood:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/blood/PlayerBlood");
        }
    }
    REG("ui.game.blood.PlayerBloodUI",PlayerBloodUI);
    export class ShipBloodUI extends Scene {
		public box_flag:Laya.Box;
		public txt_blood:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/blood/ShipBlood");
        }
    }
    REG("ui.game.blood.ShipBloodUI",ShipBloodUI);
}
export module ui.game.dungeon {
    export class DungeonCampSceneUI extends Scene {
		public img_bg:Laya.Image;
		public box_content:Laya.Box;
		public btn_back:Laya.Button;
		public boxH_level:Laya.HBox;
		public img_level:Laya.Image;
		public box_award:Laya.Box;
		public img_boxAward:Laya.Image;
		public box_awardStar:Laya.Box;
		public btn_start:Laya.Button;
		public box_gameBanner:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/dungeon/DungeonCampScene");
        }
    }
    REG("ui.game.dungeon.DungeonCampSceneUI",DungeonCampSceneUI);
    export class DungeonItemUI extends Scene {
		public img_bg:Laya.Image;
		public box_num:Laya.Box;
		public box_awardStar:Laya.Box;
		public img_mark:Laya.Image;
		public icon_hand:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/dungeon/DungeonItem");
        }
    }
    REG("ui.game.dungeon.DungeonItemUI",DungeonItemUI);
    export class DungeonOverSceneUI extends Scene {
		public grp_center:Laya.Box;
		public img_bg:Laya.Image;
		public box_win:Laya.Box;
		public box_star:Laya.Box;
		public img_hp:Laya.Image;
		public btn_sure:Laya.Button;
		public btn_shareVideo:Laya.Button;
		public btn_share:Laya.Button;
		public box_fail:Laya.Box;
		public btn_sure1:Laya.Button;
		public btn_shareVideo1:Laya.Button;
		public btn_share1:Laya.Button;
		public box_fail1:Laya.Box;
		public btn_home:Laya.Button;
		public btn_restart:Laya.Button;
		public box_award:Laya.Box;
		public img_boxAward:Laya.Image;
		public box_awardStar:Laya.Box;
		public box_gameBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/dungeon/DungeonOverScene");
        }
    }
    REG("ui.game.dungeon.DungeonOverSceneUI",DungeonOverSceneUI);
    export class DungeonSceneUI extends Scene {
		public panel_map:Laya.Panel;
		public box_dungeon:Laya.Box;
		public btn_back:Laya.Button;
		public box_bottom:Laya.Box;
		public btn_pig:Laya.Button;
		public box_award:Laya.Box;
		public img_boxAward:Laya.Image;
		public box_awardStar:Laya.Box;
		public box_gameBanner:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/dungeon/DungeonScene");
        }
    }
    REG("ui.game.dungeon.DungeonSceneUI",DungeonSceneUI);
    export class EnemyCampItemUI extends Scene {
		public img_icon:Laya.Image;
		public lab_num:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/dungeon/EnemyCampItem");
        }
    }
    REG("ui.game.dungeon.EnemyCampItemUI",EnemyCampItemUI);
}
export module ui.game {
    export class GamePauseSceneUI extends Scene {
		public img_bg:Laya.Image;
		public grp_center:Laya.Box;
		public btn_home:Laya.Button;
		public btn_restart:Laya.Button;
		public btn_continue:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GamePauseScene");
        }
    }
    REG("ui.game.GamePauseSceneUI",GamePauseSceneUI);
    export class GameSceneUI extends Scene {
		public box_game:Laya.Box;
		public box_pop:Laya.Box;
		public icon_start:Laya.Image;
		public icon_guide:Laya.Image;
		public icon_guide_hand:Laya.Image;
		public box_tip:Laya.Box;
		public btn_pause:Laya.Box;
		public btn_model:Laya.Box;
		public btn_record:Laya.Image;
		public box_gameBanner:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameScene");
        }
    }
    REG("ui.game.GameSceneUI",GameSceneUI);
}
export module ui.game.regatta {
    export class RegattaItemUI extends Scene {
		public box_center:Laya.Box;
		public box_start:Laya.Box;
		public box_mid:Laya.Box;
		public box_end:Laya.Box;
		public box_reward:Laya.Box;
		public img_slot:Laya.Image;
		public boxV_booster:Laya.VBox;
		public img_jt:Laya.Image;
		public img_pass:Laya.Image;
		public box_star:Laya.Box;
		public boxH_star:Laya.HBox;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/regatta/RegattaItem");
        }
    }
    REG("ui.game.regatta.RegattaItemUI",RegattaItemUI);
    export class RegattaOverSceneUI extends Scene {
		public grp_center:Laya.Box;
		public img_bg:Laya.Image;
		public box_content:Laya.Box;
		public panel_rank:Laya.Panel;
		public btn_sure:Laya.Button;
		public btn_share:Laya.Button;
		public btn_shareVideo:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/regatta/RegattaOverScene");
        }
    }
    REG("ui.game.regatta.RegattaOverSceneUI",RegattaOverSceneUI);
    export class RegattaSceneUI extends Scene {
		public img_bg:Laya.Image;
		public panel_map:Laya.Panel;
		public box_zone:Laya.Box;
		public btn_back:Laya.Button;
		public btn_start:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/regatta/RegattaScene");
        }
    }
    REG("ui.game.regatta.RegattaSceneUI",RegattaSceneUI);
}
export module ui.game.ship {
    export class Ship110001UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110001");
        }
    }
    REG("ui.game.ship.Ship110001UI",Ship110001UI);
    export class Ship110002UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110002");
        }
    }
    REG("ui.game.ship.Ship110002UI",Ship110002UI);
    export class Ship110003UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110003");
        }
    }
    REG("ui.game.ship.Ship110003UI",Ship110003UI);
    export class Ship110004UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110004");
        }
    }
    REG("ui.game.ship.Ship110004UI",Ship110004UI);
    export class Ship110005UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110005");
        }
    }
    REG("ui.game.ship.Ship110005UI",Ship110005UI);
    export class Ship110101UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110101");
        }
    }
    REG("ui.game.ship.Ship110101UI",Ship110101UI);
    export class Ship110102UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110102");
        }
    }
    REG("ui.game.ship.Ship110102UI",Ship110102UI);
    export class Ship110103UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110103");
        }
    }
    REG("ui.game.ship.Ship110103UI",Ship110103UI);
    export class Ship110104UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110104");
        }
    }
    REG("ui.game.ship.Ship110104UI",Ship110104UI);
    export class Ship110105UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110105");
        }
    }
    REG("ui.game.ship.Ship110105UI",Ship110105UI);
    export class Ship110201UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public behind:Laya.Box;
		public box1:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110201");
        }
    }
    REG("ui.game.ship.Ship110201UI",Ship110201UI);
    export class Ship110202UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110202");
        }
    }
    REG("ui.game.ship.Ship110202UI",Ship110202UI);
    export class Ship110203UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110203");
        }
    }
    REG("ui.game.ship.Ship110203UI",Ship110203UI);
    export class Ship110204UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110204");
        }
    }
    REG("ui.game.ship.Ship110204UI",Ship110204UI);
    export class Ship110205UI extends Scene {
		public box_ship:Laya.Box;
		public box_blood:Laya.Box;
		public box_ui:Laya.Box;
		public box1:Laya.Box;
		public behind:Laya.Box;
		public middle:Laya.Box;
		public box_player3:Laya.Box;
		public box_player1:Laya.Box;
		public box_player2:Laya.Box;
		public box_player5:Laya.Box;
		public box_player4:Laya.Box;
		public front:Laya.Box;
		public icon_booster:Laya.Image;
		public icon_ship:Laya.Box;
		public box_detail:Laya.Box;
		public box_col1:Laya.Box;
		public box_col2:Laya.Box;
		public box_col3:Laya.Box;
		public box_col4:Laya.Box;
		public box_col5:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/ship/Ship110205");
        }
    }
    REG("ui.game.ship.Ship110205UI",Ship110205UI);
}
export module ui.game.test {
    export class ShipUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/test/Ship");
        }
    }
    REG("ui.game.test.ShipUI",ShipUI);
}
export module ui.home.award {
    export class AwardSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_title:Laya.Image;
		public panel_award:Laya.Panel;
		public box_award:Laya.Box;
		public btn_get:Laya.Button;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/award/AwardScene");
        }
    }
    REG("ui.home.award.AwardSceneUI",AwardSceneUI);
    export class GiftItemUI extends Scene {
		public lab_name:Laya.Label;
		public img_icon:Laya.Image;
		public boxH_star:Laya.HBox;
		public btn_video:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/award/GiftItem");
        }
    }
    REG("ui.home.award.GiftItemUI",GiftItemUI);
    export class GoodsItemUI extends Scene {
		public lab_name:Laya.Label;
		public img_content:Laya.Image;
		public img_icon:Laya.Image;
		public lab_num:Laya.Label;
		public btn_video:Laya.Button;
		public img_mult:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/award/GoodsItem");
        }
    }
    REG("ui.home.award.GoodsItemUI",GoodsItemUI);
    export class PropItemUI extends Scene {
		public lab_lv:Laya.Label;
		public img_jd:Laya.Image;
		public img_icon:Laya.Image;
		public boxH_star:Laya.HBox;
		public boxH_ship:Laya.HBox;
		public img_shipHp:Laya.Image;
		public lab_shipHp:Laya.Label;
		public lab_shipSlot:Laya.Label;
		public boxH_cat:Laya.HBox;
		public img_catAtk:Laya.Image;
		public lab_catAtk:Laya.Label;
		public lab_catHp:Laya.Label;
		public lab_catCrit:Laya.Label;
		public boxH_booster:Laya.HBox;
		public lab_boosterHp:Laya.Label;
		public lab_boosterCd:Laya.Label;
		public lab_name:Laya.Label;
		public img_detail:Laya.Image;
		public img_xiyou:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/award/PropItem");
        }
    }
    REG("ui.home.award.PropItemUI",PropItemUI);
}
export module ui.home.common {
    export class NoVacancyUI extends Scene {
		public grp_center:Laya.Box;
		public btn_back:Laya.Button;
		public btn_ok:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/common/NoVacancy");
        }
    }
    REG("ui.home.common.NoVacancyUI",NoVacancyUI);
}
export module ui.home.foster {
    export class AdventureEmenySceneUI extends Scene {
		public img_bg:Laya.Image;
		public box_main:Laya.Box;
		public box_ship:Laya.Box;
		public box_detail:Laya.Box;
		public panel_rank:Laya.Panel;
		public btn_close:Laya.Image;
		public btn_fight:Laya.Image;
		public img_sun:Laya.Image;
		public txt_sky:Laya.Label;
		public txt_water:Laya.Label;
		public txt_underWater:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/foster/AdventureEmenyScene");
        }
    }
    REG("ui.home.foster.AdventureEmenySceneUI",AdventureEmenySceneUI);
    export class AdventureSceneUI extends Scene {
		public box_main:Laya.Box;
		public box_detail:Laya.Box;
		public box_sale:Laya.Box;
		public boxH_gold:Laya.HBox;
		public txt_gold:Laya.Label;
		public box_ship:Laya.Box;
		public box_detail_click:Laya.Box;
		public img_detail:Laya.Image;
		public icon_remove:Laya.Image;
		public box_selected:Laya.Box;
		public panel_selecte:Laya.Panel;
		public boxView:Laya.Box;
		public btn_pre:Laya.Image;
		public btn_next:Laya.Image;
		public box_pop:Laya.Box;
		public img_expTip:Laya.Image;
		public btn_close:Laya.Image;
		public btn_fight:Laya.Image;
		public img_sun:Laya.Image;
		public txt_sky:Laya.Label;
		public txt_water:Laya.Label;
		public txt_underWater:Laya.Label;
		public icon_set:Laya.Image;
		public icon_guide_hand:Laya.Image;
		public icon_guide_lab:Laya.Image;
		public btn_help:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/foster/AdventureScene");
        }
    }
    REG("ui.home.foster.AdventureSceneUI",AdventureSceneUI);
    export class DevourInfoItemUI extends Scene {
		public lab_lv:Laya.Label;
		public boxH_ship:Laya.HBox;
		public img_shipHp:Laya.Image;
		public lab_shipHp:Laya.Label;
		public lab_shipSlot:Laya.Label;
		public boxH_cat:Laya.HBox;
		public img_catAtk:Laya.Image;
		public lab_catAtk:Laya.Label;
		public lab_catHp:Laya.Label;
		public lab_catCrit:Laya.Label;
		public boxH_booster:Laya.HBox;
		public lab_boosterHp:Laya.Label;
		public lab_boosterCd:Laya.Label;
		public img_jd:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/foster/DevourInfoItem");
        }
    }
    REG("ui.home.foster.DevourInfoItemUI",DevourInfoItemUI);
    export class FosterDetailSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public lab_title:Laya.Label;
		public img_icon:Laya.Image;
		public btn_close:Laya.Button;
		public lab_name:Laya.Label;
		public lab_desc:Laya.Label;
		public lab_type:Laya.Label;
		public lab_rarity:Laya.Label;
		public boxH_star:Laya.HBox;
		public box_ship:Laya.Box;
		public img_shipHp:Laya.Image;
		public lab_shipHp:Laya.Label;
		public lab_shipSlot:Laya.Label;
		public box_cat:Laya.Box;
		public img_catAtk:Laya.Image;
		public lab_catAtk:Laya.Label;
		public lab_catCrit:Laya.Label;
		public lab_catHp:Laya.Label;
		public box_booster:Laya.Box;
		public lab_boosterHp:Laya.Label;
		public lab_boosterCd:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/foster/FosterDetailScene");
        }
    }
    REG("ui.home.foster.FosterDetailSceneUI",FosterDetailSceneUI);
    export class FosterItemUI extends Scene {
		public img_bg:Laya.Image;
		public img_select:Laya.Image;
		public box_player:Laya.Box;
		public img_rank:Laya.Image;
		public lab_rank:Laya.Label;
		public lab_name:Laya.Label;
		public lab_combat:Laya.Label;
		public box_award:Laya.Box;
		public img_icon:Laya.Image;
		public img_state:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/foster/FosterItem");
        }
    }
    REG("ui.home.foster.FosterItemUI",FosterItemUI);
}
export module ui.home {
    export class HomeSceneUI extends Scene {
		public box_main:Laya.Box;
		public box_view:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/HomeScene");
        }
    }
    REG("ui.home.HomeSceneUI",HomeSceneUI);
    export class MainSceneUI extends Scene {
		public img_bg:Laya.Image;
		public img_road:Laya.Image;
		public box_ship:Laya.Box;
		public btn_game1:Laya.Button;
		public lab_rank:Laya.Label;
		public btn_game2:Laya.Button;
		public btn_setting:Laya.Button;
		public box_right:Laya.Box;
		public btn_task:Laya.Button;
		public btn_sign:Laya.Button;
		public btn_lottery:Laya.Button;
		public btn_treasure:Laya.Button;
		public lab_videoTimes:Laya.Label;
		public box_treasure:Laya.Box;
		public txt_show:Laya.Label;
		public box_gameBanner:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/MainScene");
        }
    }
    REG("ui.home.MainSceneUI",MainSceneUI);
    export class PlayerTopSceneUI extends Scene {
		public txt_nickname:Laya.Label;
		public txt_grade:Laya.Label;
		public img_gold:Laya.Box;
		public img_diamond:Laya.Box;
		public btn_add:Laya.Image;
		public img_num1:Laya.Image;
		public img_point:Laya.Image;
		public img_num2:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/PlayerTopScene");
        }
    }
    REG("ui.home.PlayerTopSceneUI",PlayerTopSceneUI);
}
export module ui.home.lottery {
    export class LotterySceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_table:Laya.Image;
		public btn_close:Laya.Button;
		public btn_lottery:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/lottery/LotteryScene");
        }
    }
    REG("ui.home.lottery.LotterySceneUI",LotterySceneUI);
}
export module ui.home.pop {
    export class PopHelpSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public icon_guide:Laya.Image;
		public btn_pre:Laya.Image;
		public btn_next:Laya.Image;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/pop/PopHelpScene");
        }
    }
    REG("ui.home.pop.PopHelpSceneUI",PopHelpSceneUI);
}
export module ui.home.relive {
    export class PopReliveUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public btn_relive:Laya.Button;
		public btn_close:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/relive/PopRelive");
        }
    }
    REG("ui.home.relive.PopReliveUI",PopReliveUI);
}
export module ui.home.set {
    export class SetSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_music:Laya.Image;
		public img_vibrate:Laya.Image;
		public img_effect:Laya.Image;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/set/SetScene");
        }
    }
    REG("ui.home.set.SetSceneUI",SetSceneUI);
}
export module ui.home.sign {
    export class SignItemUI extends Scene {
		public img_bg:Laya.Image;
		public lab_title:Laya.Label;
		public img_icon:Laya.Image;
		public lab_num:Laya.Label;
		public img_light:Laya.Image;
		public img_signed:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/sign/SignItem");
        }
    }
    REG("ui.home.sign.SignItemUI",SignItemUI);
    export class SignSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public box_sign:Laya.Box;
		public btn_close:Laya.Button;
		public img_tip:Laya.Image;
		public btn_sign:Laya.Button;
		public btn_double:Laya.Box;
		public icon_check:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/sign/SignScene");
        }
    }
    REG("ui.home.sign.SignSceneUI",SignSceneUI);
}
export module ui.home.store {
    export class StoreItemUI extends Scene {
		public lab_name:Laya.Label;
		public img_icon:Laya.Image;
		public lab_des:Laya.Label;
		public box_des:Laya.Box;
		public img_lottery:Laya.Image;
		public btn_video:Laya.Button;
		public lab_videoTimes:Laya.Label;
		public btn_dim:Laya.Button;
		public img_cast:Laya.Image;
		public btn_lottery:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/store/StoreItem");
        }
    }
    REG("ui.home.store.StoreItemUI",StoreItemUI);
    export class StoreSceneUI extends Scene {
		public grp_center:Laya.Box;
		public img_bg:Laya.Image;
		public box_content:Laya.Box;
		public panel_store:Laya.Panel;
		public box_store:Laya.Box;
		public btn_close:Laya.Button;
		public box_gameBanner:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/store/StoreScene");
        }
    }
    REG("ui.home.store.StoreSceneUI",StoreSceneUI);
}
export module ui.home.task {
    export class TaskItemUI extends Scene {
		public img_prog:Laya.Image;
		public lab_prog:Laya.Label;
		public lab_desc:Laya.Label;
		public btn_get:Laya.Button;
		public btn_video:Laya.Button;
		public img_videoTip:Laya.Image;
		public img_award:Laya.Image;
		public lab_num:Laya.Label;
		public img_xian:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/task/TaskItem");
        }
    }
    REG("ui.home.task.TaskItemUI",TaskItemUI);
    export class TaskSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_prog:Laya.Image;
		public lab_prog:Laya.Label;
		public img_light:Laya.Image;
		public img_award:Laya.Image;
		public box_task:Laya.Box;
		public box_complete:Laya.Box;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/task/TaskScene");
        }
    }
    REG("ui.home.task.TaskSceneUI",TaskSceneUI);
}
export module ui.home.treasure {
    export class OpenTreasureUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_light:Laya.Image;
		public box_ani:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/treasure/OpenTreasure");
        }
    }
    REG("ui.home.treasure.OpenTreasureUI",OpenTreasureUI);
    export class TreasureItemUI extends Scene {
		public img_icon:Laya.Image;
		public btn_open:Laya.Button;
		public img_suo:Laya.Image;
		public lab_open:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/treasure/TreasureItem");
        }
    }
    REG("ui.home.treasure.TreasureItemUI",TreasureItemUI);
    export class TreasureSceneUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public img_icon:Laya.Image;
		public img_time:Laya.Image;
		public lab_time:Laya.Label;
		public btn_close:Laya.Button;
		public btn_open:Laya.Button;
		public box_open1:Laya.Box;
		public img_openCostH:Laya.Image;
		public img_openCostM:Laya.Image;
		public box_open2:Laya.Box;
		public img_openCostD:Laya.Image;
		public btn_jump:Laya.Button;
		public box_jump1:Laya.Box;
		public img_jumpCostD:Laya.Image;
		public box_jump2:Laya.Box;
		public img_jumpCostM:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/treasure/TreasureScene");
        }
    }
    REG("ui.home.treasure.TreasureSceneUI",TreasureSceneUI);
}
export module ui.home.tt {
    export class ShareVideoUI extends Scene {
		public grp_center:Laya.Box;
		public box_content:Laya.Box;
		public txt_award:Laya.Label;
		public btn_share:Laya.Button;
		public btn_close:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/tt/ShareVideo");
        }
    }
    REG("ui.home.tt.ShareVideoUI",ShareVideoUI);
    export class TTBaoTypeGameUI extends Scene {
		public bg_:Laya.Image;
		public icon_:Laya.Image;
		public iconMask_:Laya.Image;
		public dot_:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/tt/TTBaoTypeGame");
        }
    }
    REG("ui.home.tt.TTBaoTypeGameUI",TTBaoTypeGameUI);
}
export module ui.platform.dy.wechat {
    export class DYMoreGameBannerUI extends Scene {
		public panel_list:Laya.Panel;
		public box_view1:Laya.Box;
		public box_view2:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/DYMoreGameBanner");
        }
    }
    REG("ui.platform.dy.wechat.DYMoreGameBannerUI",DYMoreGameBannerUI);
    export class DYMoreGameBoxUI extends Scene {
		public box_game:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/DYMoreGameBox");
        }
    }
    REG("ui.platform.dy.wechat.DYMoreGameBoxUI",DYMoreGameBoxUI);
    export class DYMoreGameDrawerUI extends Scene {
		public box_db:Laya.Box;
		public box_content:Laya.Box;
		public btn_switch:Laya.Button;
		public img_jt:Laya.Image;
		public img_tips_p:Laya.Image;
		public panel_list:Laya.Panel;
		public box_game1:Laya.Box;
		public box_game2:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/DYMoreGameDrawer");
        }
    }
    REG("ui.platform.dy.wechat.DYMoreGameDrawerUI",DYMoreGameDrawerUI);
    export class MainGameItemUI extends View {
		public bg:Laya.Image;
		public icon_title:Laya.Image;
		public txt_tile:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/MainGameItem");
        }
    }
    REG("ui.platform.dy.wechat.MainGameItemUI",MainGameItemUI);
    export class MainGameitem1UI extends View {
		public icon_title:Laya.Image;
		public txt_title:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/MainGameitem1");
        }
    }
    REG("ui.platform.dy.wechat.MainGameitem1UI",MainGameitem1UI);
    export class MainGameItem2UI extends View {
		public icon_title:Laya.Image;
		public txt_title:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/MainGameItem2");
        }
    }
    REG("ui.platform.dy.wechat.MainGameItem2UI",MainGameItem2UI);
    export class MoreGameBoxSingleItemUI extends Scene {
		public icon_title:Laya.Image;
		public txt_title:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/MoreGameBoxSingleItem");
        }
    }
    REG("ui.platform.dy.wechat.MoreGameBoxSingleItemUI",MoreGameBoxSingleItemUI);
    export class OpenGoldBoxSceneUI extends Scene {
		public grp_center:Laya.Box;
		public btn_click:Laya.Button;
		public icon_bar1:Laya.Image;
		public box_gameBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/OpenGoldBoxScene");
        }
    }
    REG("ui.platform.dy.wechat.OpenGoldBoxSceneUI",OpenGoldBoxSceneUI);
    export class WechatBoxUI2UI extends Scene {
		public panel_list:Laya.Panel;
		public bnt_next:Laya.Image;
		public btn_back:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/WechatBoxUI2");
        }
    }
    REG("ui.platform.dy.wechat.WechatBoxUI2UI",WechatBoxUI2UI);
    export class WechatBoxUI3UI extends View {
		public btn_back:Laya.Image;
		public bnt_next:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/WechatBoxUI3");
        }
    }
    REG("ui.platform.dy.wechat.WechatBoxUI3UI",WechatBoxUI3UI);
    export class WechatBoxUI4UI extends View {
		public bnt_next:Laya.Image;
		public btn_back:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("platform/dy/wechat/WechatBoxUI4");
        }
    }
    REG("ui.platform.dy.wechat.WechatBoxUI4UI",WechatBoxUI4UI);
}